repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--config, ./pyproject.toml, --fix, --show-fixes]  # auto fix
      - id: ruff-format

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.2.7
    hooks:
      - id: pylint
        args: [--rcfile=./pyproject.toml]
